### ISSUE TITLE
Shops/Stash do not show marker or text

### ISSUE THREAD

**Issue by RvN-DK** [JiminyKroket/Invhud#1]
Hi

I have installed the script and it works, besides shop's and stashes do not show marker or text, it is supposed not to display anything or is it because it has not been made yet ?

**Comment by JiminyKroket** [comment]
Never thought to add em :shrug:

**Comment by JiminyKroket** [comment]
Should be fixed in newest push

**Comment by RvN-DK** [comment]
I have download the newest push and it does not work at shops and with stashes the text does not show and the marker only shows a sec when opened, it does not show before i open the stash
