### ISSUE TITLE
Weapon Ammo

### ISSUE THREAD

**Issue by DandoGame** [JiminyKroket/Invhud#10]
When I drop the gun without ammo, it will have 250 bullets when I pick it up.

**Comment by JiminyKroket** [comment]
Script uses pure ESX events, you will have to find the issue there.

**Comment by JiminyKroket** [comment]
Is the thumbsup you saying you found the issue, or just acknowledging you should check your esx files?

**Comment by DandoGame** [comment]
recognizing that I should check my ESX files

**Comment by JiminyKroket** [comment]
Will assume the issue was on your end, if you find actual errors through invhud open new issue.
