### ISSUE TITLE
Weapon weights

### ISSUE THREAD

**Issue by BryBTG** [JiminyKroket/Invhud#11]
![image](https://user-images.githubusercontent.com/50550050/91207446-55fdbb00-e73b-11ea-8827-02aeb9a38388.png)
![image](https://user-images.githubusercontent.com/50550050/91207480-63b34080-e73b-11ea-9e07-e23f40ab9863.png)
![image](https://user-images.githubusercontent.com/50550050/91207668-b55bcb00-e73b-11ea-8a4a-93361de3a5e9.png)

**Comment by JiminyKroket** [comment]
I'm confused what the issue

**Comment by JiminyKroket** [comment]
Invhud does not set weapons as items, they are not accommodated as weight in the player inventory.

**Comment by JiminyKroket** [comment]
They are allowed to be shown there so players have a way to drop/give them, not so it can add to their carry weight.

**Comment by BryBTG** [comment]
So what does weights on the config do? For stashes trunks and glovebox only?

**Comment by BryBTG** [comment]
Because as i observed, when you have a full inventory 24000/24000 you can still pick or transfer weapons from trunk, stashes or glovebox.

**Comment by JiminyKroket** [comment]
Correct, weapon weights are only for handled inventories.

**Comment by JiminyKroket** [comment]
Should be working in latest push. Config option
