### ISSUE TITLE
glovebox/trunk weight

### ISSUE THREAD

**Issue by kango76** [JiminyKroket/Invhud#13]
![image](https://user-images.githubusercontent.com/39607693/91674881-468dc180-eaef-11ea-8855-52a7f4369677.png)
And stashes dont work

**Comment by JiminyKroket** [comment]
Yeah should be Classes

**Comment by kango76** [comment]
![image](https://user-images.githubusercontent.com/39607693/91675844-af2a6d80-eaf2-11ea-9a32-e09a4141c770.png)
Now I get this

**Comment by JiminyKroket** [comment]
Should be fixed in newest push, open new issue if not.
