### ISSUE TITLE
Problem with weapon shop

### ISSUE THREAD

**Issue by bertux30** [JiminyKroket/Invhud#14]
First, too much thanks for your awesome work. 
All its working good (store, vehicle trunks, wardroves, shops). Only I having problems with weapons shops (ammunations). I have the license type weapond but its seem to get for the else in the conditional, and says that dont have.  ¿Do you have the same problem or its only me?
Thanks.

**Comment by JiminyKroket** [comment]
Uhh i think the config has firearm license

**Comment by bertux30** [comment]
ok, thx. I dont see the NeedsLicense = 'firearm' in config.
