### ISSUE TITLE
Weapons with trunk and drawers

### ISSUE THREAD

**Issue by bertux30** [JiminyKroket/Invhud#15]
When you put a gun in the trunk, it disappears from my inventory but does not appear in the trunk, the same with the drawers in the house. However, the items pan, watter, etc. do work. ¿Any tip to solve it?, maybe it's me.

**Comment by JiminyKroket** [comment]
Without errors there isnt much I can

**Comment by bertux30** [comment]
no errors in the console.  
This is the sql table inventories {"cash":0,"blackMoney":0,"weapons":[],"items":{"shotcalrounds":[{"count":1,"label":"Shell Caliber Clip"}]}}  
the clip work.
¿I need to put the weaponds like normal items on the table "items" ?

**Comment by JiminyKroket** [comment]
No, weapons are not items. Youll need to add prints to your server file and
see where its failing. Line 420 of the server.lua should create the weapon
table and then add it

**Comment by bertux30** [comment]
Ok, i see this error  @invhud/server.lua:420: attempt to perform arithmetic on a nil value (field 'maxWeight')

**Comment by JiminyKroket** [comment]
Should be fixed in newest push

**Comment by bertux30** [comment]
too much Thanks again. Do you have paypal or something to make you a donation?

**Comment by bertux30** [comment]
for your work

**Comment by JiminyKroket** [comment]
Inventory hud is based off of other developers' work. There is no reason to
donate anything.

**Comment by bertux30** [comment]
ok, you fix it. Anyway you are giving me a support. Im a Java programmer but im lost with lua. Also im looking for a programmer for make modifications or create custom script. If u are interested contact me for email. albertolopeznogales@gmail.com 

I close the issue
