### ISSUE TITLE
Unable to purchase or sell items - shopType nil

### ISSUE THREAD

**Issue by JoeSzymkowiczFiveM** [JiminyKroket/Invhud#16]
Using config provided, only changing ESX1Point1 to true, trying to buy from any shop prompts "This shop does not sell items". I made sure the Type was set to "purchase", but when i print shopData.Type at the start of "TakeFromShop", it is set to 'nil'. I also tried shopData.Account and this was also nil. Store is displaying correct items, but cannot purchase or sell when shop type set appropriately. Even removing this if does not let me purchase items, I'm guessing, because SellItemToPlayer still requires shopData. I'm unable to see what's even in shopData.

**Comment by JiminyKroket** [comment]
Fixed in latest client file release
