### ISSUE TITLE
Attempt to compare nil with number

### ISSUE THREAD

**Issue by OwnerDevSoviet** [JiminyKroket/Invhud#18]
Current bug is this 
https://i.imgur.com/cWbfG8V.png
es_extended version 1.1
![image](https://user-images.githubusercontent.com/70889124/92508741-f8974e80-f1bd-11ea-9bbf-e8d1a0a85150.png)
https://i.imgur.com/wyr1Ixn.png
Line in question. 
![image](https://user-images.githubusercontent.com/70889124/92508795-14025980-f1be-11ea-8d14-7a7d24ff4d83.png)
Picture of Config.

**Comment by OwnerDevSoviet** [comment]
https://i.imgur.com/Ol9k3YB.png Image of the error code

**Comment by JiminyKroket** [comment]
Your xPlayer.getMoney is returning nil for some reason. add prints and see why

**Comment by JiminyKroket** [comment]
![image](https://user-images.githubusercontent.com/50643200/92753277-59a25c00-f34f-11ea-91e1-9595d66adfa6.png)
It is a function in ESX 1.1 still, so not sure how its returning a nil value

**Comment by JiminyKroket** [comment]
Fix pushed
