### ISSUE TITLE
Shops/Stashes does not show marker or text

### ISSUE THREAD

**Issue by RvN-DK** [JiminyKroket/Invhud#2]
I have download the newest push and at stashes the text does not show and the marker only shows a sec when opened, it does not show before i open the stash and the same with shops and while i was in the shop i noticed that the price is not there

**Comment by JiminyKroket** [comment]
Okay. Ill revert the files when I get time. If you get it sorted I'll
accept a PR

**Comment by JiminyKroket** [comment]
Fixed in newest update. Not sure if the resource usage is wrecked or not 🤷
