### ISSUE TITLE
Can't see weapons of other players with force search

### ISSUE THREAD

**Issue by Duckerr** [JiminyKroket/Invhud#20]
Using forcesearch, when opening someone's inventory it shows items but not their weapons. Changing to tplayer.loadout to tplayer.getloadout() did not work

**Comment by JiminyKroket** [comment]
Issue should be fixed in newest files, awaiting confirmation.

**Comment by Duckerr** [comment]
> Issue should be fixed in newest files, awaiting confirmation.

It now shows the most recent weapon the player has equipped, doesnt show all of them they have

**Comment by JiminyKroket** [comment]
I don't mean to ignore this issue or anything. I simply have no way to do any testing of this problem myself though. Any and all advances with this issue will need to be done by the community unfortunately.
