### ISSUE TITLE
Update licenses on shop interaction

### ISSUE THREAD

**Issue by destruct1** [JiminyKroket/Invhud#22]
For shops that require licenses, if the player got the license after the resource being initialized, then the shop will deny them access.

It may just be me, idk

**Comment by JiminyKroket** [comment]
Event added, info added to README. You'll need to trigger the license refresh yourself(not having a license check loop)

**Comment by JiminyKroket** [comment]
Re-adjusted to auto search for license if license is not initially found on shop interaction
