### ISSUE TITLE
not an issue, just a question

### ISSUE THREAD

**Issue by destruct1** [JiminyKroket/Invhud#23]
Hello, first of all, thanks for developing this it's super nice so far.

Just a question here, the pictures included in this issue: https://github.com/JiminyKroket/Invhud/issues/11
Is the inventory weight in the hud a default feature to your resource, if it is do I have to enable it somehow?
The hud on my server with the latest version looks like this: https://i.imgur.com/pUOjxNv.png

**Comment by JiminyKroket** [comment]
If all files were replaced including the js files the. Kt should display like this

**Comment by destruct1** [comment]
I understand, so what you're saying is theirs is custom?

**Comment by JiminyKroket** [comment]
No. What all files do you replace when you update?

**Comment by JiminyKroket** [comment]
Oh I'm very sorry, your image is how standard invhud has player inventory. The image shown in that issue does have an adjusted .css file...

**Comment by destruct1** [comment]
Gotcha, thanks!

**Comment by JiminyKroket** [comment]
![image](https://user-images.githubusercontent.com/50643200/95658371-81681980-0adf-11eb-9ecf-0fddf53e7cb8.png)
![image](https://user-images.githubusercontent.com/50643200/95658374-875dfa80-0adf-11eb-875e-5afa90d5d1ab.png)

**Comment by destruct1** [comment]
@JiminyKroket Does that picture mean you've made it a feature of invhud or just showing that it can be done?

**Comment by JiminyKroket** [comment]
Should be a feature now
