### ISSUE TITLE
not an issue , just a question

### ISSUE THREAD

**Issue by DrBlackBeard095** [JiminyKroket/Invhud#25]
Do u have a discord , want to ask about the esx_gruppe6 job

**Comment by JiminyKroket** [comment]
I do not. Have you commented on the gruppe6 git? I'm sorry I haven't seen it. The only discord I actively participate in support at is https://discord.com/invite/8afXRrA

**Comment by JiminyKroket** [comment]
Will continue further correspondence there.

**Comment by JiminyKroket** [comment]
Ah it is archived I see now.
