### ISSUE TITLE
Unable to drag

### ISSUE THREAD

**Issue by Rio358** [JiminyKroket/Invhud#26]
using latest repo, ability to drag items from secondary inventories non-op, removed previous, installed latest.

latest update is only recent change to server.

**Comment by JiminyKroket** [comment]
Hm, correct it seems. Revert to working files I suppose

**Comment by JiminyKroket** [comment]
Yeah I unfortunately have no idea what happened. Nothing in the only locations changed in the js so 🤷

**Comment by JiminyKroket** [comment]
I guess prior version used 'setItems' nui message for all inventories at some point, I failed to create the items properly. FIXED
