### ISSUE TITLE
Add Current / Max capacity to self inventory

### ISSUE THREAD

**Issue by JoeSzymkowiczFiveM** [JiminyKroket/Invhud#27]
I know this is more of an enhancement, but please add current and max weight values to the player's inventory pane. Keep up the great work. I try to contribute when possible but this one was giving me fits.

**Comment by JiminyKroket** [comment]
It should already?

**Comment by JoeSzymkowiczFiveM** [comment]
I pulled latest and it is there. Sorry about that. Keep up the great work.
