### ISSUE TITLE
give money issue

### ISSUE THREAD

**Issue by Cloddd** [JiminyKroket/Invhud#28]
![unknown](https://user-images.githubusercontent.com/65135828/98345359-da5e9b00-2014-11eb-9332-bcbaecc6cc70.png)
when i try to give money to people i get this error

**Comment by JiminyKroket** [comment]
![Screenshot_20201106-024744](https://user-images.githubusercontent.com/50643200/98345608-82a33e00-1fda-11eb-85c2-e807df23fbbd.png)
Not possible on standard Git Version
