### ISSUE TITLE
Latest Update broke compatibility with esx 1.1.5(weight+limit transition)

### ISSUE THREAD

**Issue by Rio358** [JiminyKroket/Invhud#29]
Cross referenced both the previous commit as well as the current commit when dropping esx_v1.1 compatibility in the config.

When attempting to drop/give cash,  es_extended produces the following error
SCRIPT ERROR: @es_extended/server/main.lua:380 attempt to index a nil value (local 'account') 

suspecting it's due to the at best wonky way in which 1.1.5 is constructed, still using limit in addition to weight. I've had to retool almost every release to some degree.
W/A

reverting back to pre 1.1 compatibility ditch in the config removes this issue and money can be dropped freely.

The only differences between function and non-op are the differing versions, no other resources changed.

**Comment by JiminyKroket** [comment]
What is the issue?

**Comment by JiminyKroket** [comment]
Adjust config in latest push. So tired of fucking esx god damnit
