### ISSUE TITLE
Items in trunk/glovebox/stash show names, insted of labels

### ISSUE THREAD

**Issue by BrakingESX247** [JiminyKroket/Invhud#3]
As the title says. I have a workaround locally but I think you can figure out a better way!

**Comment by JiminyKroket** [comment]
Don't know js well so probably not gonna get it done myself. Looks like it should call to the label just fine so not sure.

**Comment by BrakingESX247** [comment]
I'll see If I can clean up my fix and PR it, If that's okay?

**Comment by JiminyKroket** [comment]
![image](https://user-images.githubusercontent.com/50643200/86523548-d71f8c80-be33-11ea-8077-f70f40f59d96.png)
Fixed in newest push

**Comment by BrakingESX247** [comment]
Hooray!
