### ISSUE TITLE
this is not a issue

### ISSUE THREAD

**Issue by Cloddd** [JiminyKroket/Invhud#30]
hi, i want to say that your invhud is the best right now, i have only a question: i want to use the sell option but there's no example in the config to use it, can u make me a quick one, sorry for the inconvenience

**Comment by JiminyKroket** [comment]
The config lists the possible store types in the comments of the Config.Shops section
 -- SET ALL SHOP INFORMATION HERE: TABLE NAME IS STORE NAME, TYPE(TYPE OF SHOP, 'purchase', 'sell', 'mix' AVAILABLE, CHOOSE WHAT THE PLAYER CAN DO AT THAT SHOP),
	-- ACCOUNT(PLAYER ACCOUNT TO GIVE/TAKE MONEY FROM), LOCATIONS(SHOP LOCATIONS), SOCIETY(SET SOCIETY NAME TO PAY TO/FROM, SET false IF NO SOCIETY IS USED),
	-- BUYBACK(SET VALUE FROM 0.0-1.0, AMOUNT OF ITEM PRICE GIVEN WHEN SELLING TO SHOP), ITEMS(ITEMS SHOP CAN SELL/BUY), 
	-- MARKERS(USE MARKERS?, WHAT SHAPE?, HOW FAR?, SHOW NAME?, WHAT COLOR?), BLIPS(USE BLIPS?, WHAT PICTURE?, WHAT COLOR?, HOW BIG?, WHERE TO DISPLAY?)

You simply set the Type to 'sell' or 'mix' to allow players to sell items back to the store

**Comment by Cloddd** [comment]
u have misunderstood what im meaning. there's the purchase type of config but not the sell or mix.

**Comment by JiminyKroket** [comment]
What do you need an example of? You change it to mix or sell

**Comment by JiminyKroket** [comment]
Read the comments that are legitimately LITTERED throughout the config file
that describe EVERY single option available.
