### ISSUE TITLE
shops problems

### ISSUE THREAD

**Issue by Cloddd** [JiminyKroket/Invhud#33]
hi, i have some problems with the shops, if i set in config.society.name a job name, everyone can go inside that blip and use get all the items inside it

**Comment by JiminyKroket** [comment]
Thats how its supposed to work

**Comment by Cloddd** [comment]
so what is that society thing made for?

**Comment by JiminyKroket** [comment]
Boss menu

**Comment by Cloddd** [comment]
well ok then, ill change inventory because i need that feature on inventory

**Comment by JiminyKroket** [comment]
Lol okee doke. You didnt even ask if was possible :kek:

**Comment by Cloddd** [comment]
i didnt asked because i have seen the code, i mean for making that thing possible u need to rework a lot of things, i m sure u dont want to do extra work only for me

**Comment by Cloddd** [comment]
im an asshole so i dont think u do extra work for only  a person and free

**Comment by JiminyKroket** [comment]
The most recent update pushed it.
