### ISSUE TITLE
weapon attachments saving

### ISSUE THREAD

**Issue by Cloddd** [JiminyKroket/Invhud#34]
after the new inventory update, i noticed that the script now saves the attachements for weapon, which is good, but now i have a problem, if i remove my attachments from weapon , using esx code(not the natives) and if i drop the weapon and i get it back, the attachment appears another time. i think the problem of this  thing is because of some loop  in the inventory or something like that.

**Comment by JiminyKroket** [comment]
Drop like on the ground?

**Comment by Cloddd** [comment]
yea

**Comment by Cloddd** [comment]
im making a video so i can share with you

**Comment by Cloddd** [comment]
https://streamable.com/w6bw96

**Comment by Cloddd** [comment]
any news?

**Comment by JiminyKroket** [comment]
![Screenshot_20201211-092954](https://user-images.githubusercontent.com/50643200/101922361-9d497380-3b93-11eb-8bed-faa5b03705c0.png)
![Uploading Screenshot_20201211-092804.png…]()

**Comment by JiminyKroket** [comment]
Invhud doesnt control dropping/picking up items

**Comment by JiminyKroket** [comment]
![Screenshot_20201211-092804](https://user-images.githubusercontent.com/50643200/101922687-05985500-3b94-11eb-94fb-cf756d1e7b9f.png)

**Comment by Cloddd** [comment]
i dont know man, i searched in es_extended but the drops in 1.1 doesnt handle the attachments also

**Comment by JiminyKroket** [comment]
Yes it does though? Thats literally its job

**Comment by JiminyKroket** [comment]
The video you sent shows you dropping the item and losing the silencer at
the same time. i.e. You are losing the suppressor when dropping the gun
still

**Comment by Cloddd** [comment]
yea found it, lol, but idk how it recive the attachment if it doesnt exist

**Comment by JiminyKroket** [comment]
Idk either

**Comment by JiminyKroket** [comment]
I know if i have a gun with attachments and drop it, then give myself a new
gun, I do not have the attachments still. I can not test removing the
attachment then dropping it
