### ISSUE TITLE
Storing 2 same type weapons

### ISSUE THREAD

**Issue by Korekx** [JiminyKroket/Invhud#35]
When you want to store same type of weapon that you already have inside stash/property/trunk it gives that 
![obraz](https://user-images.githubusercontent.com/73514058/102339157-116d8800-3f95-11eb-8961-038c666a6fe6.png)

**Comment by JiminyKroket** [comment]
No. The ammo is included in weight

**Comment by Korekx** [comment]
i know but as you can see it is 10/500kg so why can't i throw it in?

**Comment by Korekx** [comment]
can't stash weapon with more than 50 ammo
i tried to disable ammo weight but it still does the same

**Comment by JiminyKroket** [comment]
Hoq did you disable ammo weight?

**Comment by JiminyKroket** [comment]
![image](https://user-images.githubusercontent.com/50643200/102451846-e6b81980-3ffe-11eb-9def-a50b9b169d1a.png)

**Comment by JiminyKroket** [comment]
![image](https://user-images.githubusercontent.com/50643200/102451873-f6cff900-3ffe-11eb-8143-919d81ffe106.png)

**Comment by JiminyKroket** [comment]
I have, two, of the exact same weapon, with both having more than 50 ammunition... and everything works
