### ISSUE TITLE
weapons with ammo

### ISSUE THREAD

**Issue by xrtw** [JiminyKroket/Invhud#38]
cant store into trunk weapons with ammo, because it shows not detected weight or something... looks like its so heavy or something like this.

**Comment by JiminyKroket** [comment]
Why is this opened as an issue? You literally explained why they don't fit.
You have the gun weight too heavy for the amount of ammo the person wants
to store. Make guns weigh 1.

**Comment by JiminyKroket** [comment]
If you are saying the script is using a default weight for a weapon then
add it to the proper table so it doesn't default

**Comment by xrtw** [comment]
i have written all weights in database also in config of invhud. but if weapon is with ammo, so it doesnt find weight of it and makes it so heavy by script default

**Comment by xrtw** [comment]
it only happens if weapon has more than 100 ammo

**Comment by JiminyKroket** [comment]
Ammo adds to weight. Not an issue. Its how the math works

**Comment by xrtw** [comment]
how can i make it to weight less?

**Comment by JiminyKroket** [comment]
Adjust the weight math

**Comment by xrtw** [comment]
hello, made 2 screenshots with ammo. If you have no ammo, you can store a pistol with weight of it - 80. if you have bullets ~100, you cant store it. tried to make larger trunk inventory so i could, but weight was only 81 with 100 bullets.. 
https://imgur.com/a/uU7UuNo

**Comment by xrtw** [comment]
go server.lua
change from
if doRound(total, 2) + doRound(itemWeight, 2) > doRound(totWeight, 2) then
to
if doRound(total, 2) + doRound(itemWeight*0.01, 2) > doRound(totWeight, 2) then
