### ISSUE TITLE
can get weapon weight 

### ISSUE THREAD

**Issue by xrtw** [JiminyKroket/Invhud#40]
hello i cant get weapon weight, is it possible to make that it would show in server console which weapon is that?
https://github.com/JiminyKroket/Invhud/blob/master/invhud/server.lua#L248
https://github.com/JiminyKroket/Invhud/blob/master/invhud/server.lua#L136

**Comment by JiminyKroket** [comment]
Missed two of them, add
for '..k..'
after
Weapon weight not set in the server prints
