### ISSUE TITLE
Issue with the search

### ISSUE THREAD

**Issue by kurlan98** [JiminyKroket/Invhud#41]
When you search the menu give a message the second inventory is opened.
![xD](https://user-images.githubusercontent.com/80090661/110078842-50baa200-7d56-11eb-83c9-5b47c0b21d9f.png)

**Comment by kurlan98** [comment]
im trying to use the force search for the police job and mafia or gangs menu.

**Comment by JiminyKroket** [comment]
Players need to enter their own inventory prior to another trying to search them. If the issue is something other than that, find the actual issue, find a solution, make a PR.
