### ISSUE TITLE
Weapons and Weight

### ISSUE THREAD

**Issue by Wollffus** [JiminyKroket/Invhud#43]
I can not put weapons away in trunks or stashes when they have ammo. When they do not have ammo i can, but can not take them back out. 

I can not seem to figure out where to change the amount of weight a player can hold.

The new hotbar update is amazing besides that

**Comment by xrtw** [comment]
go server.lua
change from
`if doRound(total, 2) + doRound(itemWeight, 2) > doRound(totWeight, 2) then`
to
`if doRound(total, 2) + doRound(itemWeight*0.01, 2) > doRound(totWeight, 2) then`

**Comment by JiminyKroket** [comment]
Oi is there a thing I need to fix whoops

**Comment by Wollffus** [comment]
how do i make it so we can carry more than 24 lbs
