### ISSUE TITLE
after hotbar IsControlJustReleased not working

### ISSUE THREAD

**Issue by xrtw** [JiminyKroket/Invhud#45]
hello, great update for hotbars! 
seems not working anymore these keys
`IsControlJustReleased(0, 157)`
`IsControlJustReleased(0, 158)`
`IsControlJustReleased(0, 160)`

**Comment by JiminyKroket** [comment]
Those are disabled now so of course it wont work.

**Comment by xrtw** [comment]
sorry, missed it :D if i enable, so hotbar wont work as it should?

**Comment by JiminyKroket** [comment]
IsDisabledControlJustWhatever

**Comment by JiminyKroket** [comment]
JustReleased/JustPressed
