### ISSUE TITLE
trunk and shops not working

### ISSUE THREAD

**Issue by gorerdrew** [JiminyKroket/Invhud#5]
As the title states the trunks and shops will not open for me, I have disabled our other shops and inventory hud systems. I do see the blips and markers for shops but when I go up to them I can not access them. Also for the trunks F2 will not open anything other than my personal inventory. Any help would be appreciated

**Comment by JiminyKroket** [comment]
Did you change the open key to f2?

**Comment by gorerdrew** [comment]
by default f2 opens the menu fro me i didnt change it

**Comment by gorerdrew** [comment]
i tried E and f2 for shops

**Comment by JiminyKroket** [comment]
invhud default key is 82, which is ,

**Comment by JiminyKroket** [comment]
![image](https://user-images.githubusercontent.com/50643200/90526849-7f648880-e136-11ea-8a89-a7723be2653e.png)

**Comment by JiminyKroket** [comment]
Idk what inventory is opening with f2

**Comment by JiminyKroket** [comment]
All inventories handled in script use the one key as well

**Comment by gorerdrew** [comment]
im a moron
