### ISSUE TITLE
Weapon getting put away when empty

### ISSUE THREAD

**Issue by xOblixion** [JiminyKroket/Invhud#50]
Is there a way to disable the weapon being holstered when empty?

When the gun reaches 0, handing the gun back to the PED so they keep the gun in hand rather then having it disappear. 

Any solutions?

**Comment by JiminyKroket** [comment]
Don't think so, pretty sure that's like, hard coded into GTA 🤷

**Comment by JiminyKroket** [comment]
https://docs.fivem.net/natives/?_0x2A7B50E
SetWeaponsNoAutoswap(true)
CFX Native added in place to do just this thing
