### ISSUE TITLE
inventory already opened

### ISSUE THREAD

**Issue by maxcamorra** [JiminyKroket/Invhud#52]
sometimes i cant enter the trunk and gbox, it tells me already opened although its not opened by anyone

**Comment by Wollffus** [comment]
same thing happens to us

**Comment by JiminyKroket** [comment]
Find the actual issue, figure out the fix for it, and make a PR

**Comment by Wollffus** [comment]
Im good man, ill fix it and at that point theres no reason for a pull request. Being a dick gets you nowhere. I was more making you aware of your broken script asshole (:

**Comment by JiminyKroket** [comment]
Its an open source fork of SOMEONE else's work, asshole. So help make it
fucking better or naff yourself shitter

**Comment by JiminyKroket** [comment]
"I'll fix it and then there is no reason to PR" It's literally that mindset
that's fucking wrong with the FiveM community. Beg and plead for it to be
fixed by someone but refuse to help others who need it.

**Comment by Wollffus** [comment]
No one begged nor pleaded Zach relax yourself. A simple question was asked that upset you because your shits broken and you couldn’t fix it, it’s fiiine we handled it

**Comment by maxcamorra** [comment]
You can tell me how you handled it?

**Comment by JiminyKroket** [comment]
😂 Kid my shits not broken. Invhud is MY fork and works exactly as I need
it to. Everything related to multiple people doesnt actually matter to me

**Comment by JiminyKroket** [comment]
Also Wolf uhh not a single question was asked. Two comments that gave no
actual assistance to sorting the problem were said.
