### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by maxcamorra** [JiminyKroket/Invhud#56]
I just found this error for first time in the console:

[       script:invhud] SCRIPT ERROR: @invhud/server.lua:207: attempt to index a nil value (local 'tPlayer')
[       script:invhud] > TriggerServerCallback (@es_extended/server/functions.lua:160)
[       script:invhud] > handler (@es_extended/server/common.lua:71)

**Comment by JiminyKroket** [comment]
Fixed in latest update. Ensure to thoroughly adjust config for new settings
