### ISSUE TITLE
Open inventory

### ISSUE THREAD

**Issue by Nymeria21** [JiminyKroket/Invhud#57]
Hello, a question how I could use f2 as a key to open the inventory to everyone? I have tried many things, but it does not work for me. Thanks in advance.

**Comment by JiminyKroket** [comment]
Read the config options and set it up right

**Comment by Nymeria21** [comment]
Thanks. One more thing I have a problem with the weapons, it does not allow me to move the weapons between inventories I get this error on the console.
![image](https://user-images.githubusercontent.com/51028651/114301438-35fdea80-9ac5-11eb-8b6e-722c3a2cdca7.png)

![image](https://user-images.githubusercontent.com/51028651/114301479-69407980-9ac5-11eb-8a38-a220df255bd1.png)
Thanks and sorry for the inconvenience.

**Comment by JiminyKroket** [comment]
newWeight or xPlayer.weight are not numbers, they are actually not anything according to the error
