### ISSUE TITLE
Inventory is already open bug.

### ISSUE THREAD

**Issue by DrunkWhiteKid** [JiminyKroket/Invhud#64]
Every now and then when accessing a stash and or trunk the next person to do so will get an (Inventory is already open) notification. I've placed stashes for PD and gangs, and it happens when the stash and or vehicle has allot of traffic in and out of it. sometimes it can be just two people grinding placing items and taking them out this will occur. (i dnt mean like as in one is actually in the inventory.) They could be all the way across the map the inventory is closed but the next person to open it gets the notification and is unable to access it.

I've tried to understand the problem more but I've had no luck. I'm very new to lua and fivem development but i usually try and solve problems myself because i wish to learn more. But sometimes i have to admit defeat and post an issue or open a ticket xD

**Comment by BryBTG** [comment]
unquote lines on 211

**Comment by ChrisHDev** [comment]
@BryBTG  what line 211? I have been encountering this issue for awhile now and still cant figure it out

**Comment by JiminyKroket** [comment]
Bry is referring to the server file which handles the inventory open checks, specifically line 211(and all other corresponding lines) where the if statement checks for the inventory being open. Remove any check for if the inventory is opened, and it won't matter if the inventory is already opened.

**Comment by ChrisHDev** [comment]
Ok. Thank you.
