### ISSUE TITLE
how to make inventory not reachable till server restart

### ISSUE THREAD

**Issue by xrtw** [JiminyKroket/Invhud#66]
open a trunk, drop an item from hotbar into the trunk and this is how it locks, it shows that somebody else is using it, so you need to wait server restart to reach inventory again

**Comment by JiminyKroket** [comment]
" it shows that somebody else is using it"
As in, even the player that just put the item into the second inventory can't use that inventory anymore as well?

**Comment by xrtw** [comment]
> " it shows that somebody else is using it"
> As in, even the player that just put the item into the second inventory can't use that inventory anymore as well?

the one who makes this, he can use, but others cant
