### ISSUE TITLE
No more inventory hud

### ISSUE THREAD

**Issue by Wollffus** [JiminyKroket/Invhud#7]
Seems that when we have the inventory hud all is well for a few hours, and than all the sudden people can not open the hud anymore and we have to stop/start the resource to fix the issue. any ideas?

**Comment by JiminyKroket** [comment]
print in the control press and see where its stopping running.

**Comment by JiminyKroket** [comment]
Should be fixed in newest update

**Comment by JiminyKroket** [comment]
Should be fixed in newest push, open new issue if not.
