### ISSUE TITLE
Cannot open Stashes

### ISSUE THREAD

**Issue by kango76** [JiminyKroket/Invhud#8]
No errors for some reason after awhile cannot open stashes still see marker though

Edit: Similar to issue https://github.com/JiminyKroket/Invhud/issues/7 maybe same

**Comment by JiminyKroket** [comment]
print in the control press and see where its stopping running.

**Comment by JiminyKroket** [comment]
What is "after a while". Can you possibly get repro steps for me?

**Comment by JiminyKroket** [comment]
Stashes are broke

**Comment by JiminyKroket** [comment]
Fixed in newest update

**Comment by JiminyKroket** [comment]
Should be fixed in newest push, open new issue if not.
